### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Liagson** [Liagson/godus-style-landscape-generator#1]
- [x] Add irregular square grid
- [ ] Delete hidden polys
- [x] Cliffs / sharp slopes
- [ ] Trees
- [ ] Rivers
- [ ] Waterfalls
- [ ] Lakes

**Comment by Liagson** [comment]
Irregular grid (square distortion) added in 2e092363

**Comment by Liagson** [comment]
Cliffs added in 1ee41ae (and tweaked a little in 668d3736)
